"""create_scenarios_and_update_roleplay_sessions

Revision ID: 7109830f0caf
Revises: 
Create Date: 2026-09-06 20:09:04.260950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7109830f0caf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('npc_role', sa.String(length=100), nullable=False),
    sa.Column('financial_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('initial_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_category'), 'scenarios', ['category'], unique=False)
    op.create_index(op.f('ix_scenarios_slug'), 'scenarios', ['slug'], unique=True)
    op.add_column('roleplay_sessions', sa.Column('scenario_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_roleplay_sessions_user_id'), 'roleplay_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'roleplay_sessions', 'scenarios', ['scenario_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'roleplay_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_roleplay_sessions_user_id'), table_name='roleplay_sessions')
    op.drop_column('roleplay_sessions', 'scenario_id')
    op.drop_index(op.f('ix_scenarios_slug'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_category'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
